#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build TX1801-16M-256M-SSP
on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Run shellcheck
      run: sh ./trunk/tools/shellcheck.sh
    - name: Prepare toolchain
      run: |
          cd toolchain-mipsel
          sh dl_toolchain.sh
    - name: Start build
      env:
        TNAME: TX1801
      run: |
        mkdir -p /opt/images/
        cd trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
        ################################################################################################
        ################################################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        #这里把它们配对写，避免遗忘任何一方，更好的方法是用一个宏定义比如:ReplaceConfigItem(<NAME>,<y/n>)来搞
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        echo    "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config #MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        echo    "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config #SCUTCLIENT
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config #删除配置项SOFTETHERVPN
        echo    "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config #SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config #删除配置项SOFTETHERVPN
        echo    "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config #SOFTETHERVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config #删除配置项SOFTETHERVPN
        echo    "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config #SOFTETHERVPN
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        echo    "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config #SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config #删除配置项simple-obfs混淆插件
        echo    "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config # simple-obfs混淆插件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XRAY/d' .config #删除配置项xray
        echo    "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config #集成xray执行文件（4.2M左右)，如果不集成，???
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config #删除配置项v2ray
        echo    "CONFIG_FIRMWARE_INCLUDE_V2RAY=n" >> .config #集成v2ray执行文件（3.8M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config #删除配置项trojan
        echo    "CONFIG_FIRMWARE_INCLUDE_TROJAN=n" >> .config #集成trojan执行文件(1.1M左右)，如果不集成，会从网上下载下来执行，不影响正常使用
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        echo    "CONFIG_FIRMWARE_INCLUDE_SSSERVER=n" >> .config #SS server
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        echo    "CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n" >> .config #DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        echo    "CONFIG_FIRMWARE_INCLUDE_ADBYBY=y" >> .config #adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_KOOLPROXY/d' .config #删除配置项KP广告过滤
        echo    "CONFIG_FIRMWARE_INCLUDE_KOOLPROXY=n" >> .config #KP广告过滤
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME/d' .config #删除配置项adg home
        echo    "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=n" >> .config #广告过滤adg home
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项FRPC
        echo    "CONFIG_FIRMWARE_INCLUDE_FRPC=n" >> .config #内网穿透FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项FRPS
        echo    "CONFIG_FIRMWARE_INCLUDE_FRPS=n" >> .config #内网穿透FRPS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config ##删除配置项zerotier
        echo    "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #内网穿透zerotier ~1.3M
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项TUNSAFE
        echo    "CONFIG_FIRMWARE_INCLUDE_TUNSAFE=n" >> .config #TUNSAFE
        ################################################################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
        echo    "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=n" >> .config #阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDY/d' .config #删除配置项caddy
        echo    "CONFIG_FIRMWARE_INCLUDE_CADDY=n" >> .config #在线文件管理服务
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CADDYBIN/d' .config #删除配置项caddy
        echo    "CONFIG_FIRMWARE_INCLUDE_CADDYBIN=n" >> .config #集成caddy执行文件，此文件有13M,请注意固件大小。如果不集成，会从网上下载下来执行，不影响正常使用
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYY/d' .config #删除配置项网易云解锁
        echo    "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config #网易云解锁
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WYYBIN/d' .config #删除配置项网易云解锁
        echo    "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config #网易云解锁GO版本执行文件（4M多）注意固件超大小,不集成会自动下载
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #删除配置项smartdns
        echo    "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=n" >> .config #smartdns
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN/d' .config #删除配置项smartdns
        echo    "CONFIG_FIRMWARE_INCLUDE_SMARTDNSBIN=n" >> .config #smartdns二进制文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_SRELAY=n" >> .config #可以不集成
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_OPENVPN=n" >> .config #openVPN
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_OPENSSH=n" >> .config #openssh
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n" >> .config #openssl二进制文件
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_TCPDUMP=n" >> .config #"tcpdump" utility. ~0.6MB
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_DOGCOM=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_HTOP=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_NANO=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_IPERF3=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_XUPNPD=n" >> .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW=n" >> .config
        ##########################################CPU超频###############################################################
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OC/d' .config
        echo    "CONFIG_FIRMWARE_INCLUDE_OC=n" >> .config #CPU超频开关
        sed -i '/CONFIG_FIRMWARE_MT7621_OC/d' .config
        echo    'CONFIG_FIRMWARE_MT7621_OC="0x312"' >> .config #此处填写对应频率的十六进制：1000Mhz=0x312 1100Mhz=0x362 1120Mhz=0x372 1200Mhz=0x3B2
        #########################################################################################
        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
        #格式如下：
        #sed -i '/自定义项/d' .config
        #echo "自定义项=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
        
